# Practical_6: Numpy

---

In [1]:
import numpy as np

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

In [13]:
a = np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

In [6]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

In [8]:
d = np.linspace(0, 5, 10)
print(d)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [7]:
c = np.eye(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [11]:
e = np.random.random((4,4),)
print(e)

[[0.88635397 0.6431869  0.27944565 0.77120177]
 [0.48617993 0.63641537 0.77538315 0.93340333]
 [0.3465525  0.61137264 0.0530244  0.69834141]
 [0.11148413 0.45242488 0.76736089 0.22382984]]


### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [12]:
print (e.shape)

(4, 4)


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [18]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [20]:
e = np.random.random((4,4),)
print(e)
print(type(e))

[[0.87975547 0.45302149 0.05473281 0.64844692]
 [0.55726616 0.77986523 0.01079663 0.71474493]
 [0.46766702 0.07679859 0.66049275 0.64219108]
 [0.20011684 0.34952399 0.44002053 0.6677362 ]]
<class 'numpy.ndarray'>


### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [24]:
numbers = np.arange(1,101)
num = [numbers[numbers % 2 == 0]]
print(num)

[array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])]


### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [36]:
f = np.random.randint(10,50,size=(6,6))
print(f)

[[34 36 42 37 39 31]
 [46 37 13 31 26 28]
 [32 21 40 40 33 33]
 [40 21 35 45 31 43]
 [10 29 21 31 46 41]
 [12 30 47 44 12 28]]


### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [33]:
x2 = np.random.randint(10, size=(3, 4))
print(x2)

x3 = x2[:2,:2]
print(x3)

[[0 5 1 2]
 [8 6 0 0]
 [2 1 3 6]]
[[0 5]
 [8 6]]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [42]:
j = np.arange(10)
r = np.sum(j)
print(j)
print(r)

[0 1 2 3 4 5 6 7 8 9]
45


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [45]:
g = np.random.randint(20, size=15)
print(g)

mean = np.mean(g)
median = np.median(g)
s_deviation = np.std(g)

print(mean)
print(median)
print(s_deviation)

[ 4 17  7  2  5  6  2 13  2 16 13 13  3 11 13]
8.466666666666667
7.0
5.251877970994968


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [51]:
x2 = np.random.randint(10, size=(3, 4))
print(x2)
large = np.max(x2)
small = np.min(x2)
print(small, large)

[[1 8 8 6]
 [8 8 0 9]
 [1 9 7 0]]
0 9


In [73]:
h = np.arange(0,12).reshape(3,4)
print(h)

v = np.max(h,axis=0)
print(v)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [69]:
k = np.random.random(20)
g = np.argmax(k)
print(k)
print(g)

[0.01446135 0.34875214 0.90390449 0.56357638 0.96787455 0.20785595
 0.20926349 0.89013402 0.27024314 0.25098082 0.77138134 0.77504277
 0.92898763 0.16454008 0.08084863 0.25093879 0.44965017 0.50284239
 0.58840402 0.50291887]
4


### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [77]:
d = np.arange(11)
print(d)
e = np.flip(d)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [88]:
A = np.arange(9).reshape(3,3)
print(A)
B = np.arange(9).reshape(3,3)
print(B)
C = np.multiply(A, B)
print(C)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [92]:
S = np.arange(9)
print(S)
X = np.diag(S)
print(X)

[0 1 2 3 4 5 6 7 8]
[[0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 5 0 0 0]
 [0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0 0 0 8]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [96]:
F = np.random.randint(10, size=(3, 4))
print(F)
E = np.random.randint(10, size=(3,4))
print(E)

G = np.multiply(F,E)
print(G)

[[5 6 3 5]
 [8 0 4 4]
 [0 0 1 3]]
[[9 1 3 8]
 [8 7 0 0]
 [4 3 3 3]]
[[45  6  9 40]
 [64  0  0  0]
 [ 0  0  3  9]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [103]:
T = np.random.randint(10, size=(3, 4))
print(T)
R = np.ndarray.flatten(T)
print(R)

[[2 5 6 3]
 [9 0 3 2]
 [0 3 1 8]]
[2 5 6 3 9 0 3 2 0 3 1 8]


In [104]:
T.flatten()

array([2, 5, 6, 3, 9, 0, 3, 2, 0, 3, 1, 8], dtype=int32)

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [112]:
H = np.arange(8)
print(H)

J = np.arange(8)
print(J)

C = np.vstack((H,J))
print(C)

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
[[0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]]


### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

In [113]:
H = np.arange(8)
print(H)

J = np.arange(8)
print(J)

C = np.hstack((H,J))
print(C)

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [117]:
T = np.random.randint(10, size=(3, 4))
U = np.split(T,3)
print(T)
print(U)

[[4 3 3 7]
 [4 6 1 9]
 [8 5 0 8]]
[array([[4, 3, 3, 7]], dtype=int32), array([[4, 6, 1, 9]], dtype=int32), array([[8, 5, 0, 8]], dtype=int32)]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [127]:
T = np.random.random(9).reshape(3,3)
print(T)
X = np.round(T, 2)
print(X)

[[0.98980552 0.08095347 0.45565542]
 [0.74796489 0.4946173  0.09476353]
 [0.91960269 0.68176956 0.42313833]]
[[0.99 0.08 0.46]
 [0.75 0.49 0.09]
 [0.92 0.68 0.42]]


### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [128]:
T = np.random.randint(10, size=(3, 4))
print(T)

Z = np.unique(T)
print(Z)

[[0 4 8 5]
 [8 7 7 8]
 [8 0 1 4]]
[0 1 4 5 7 8]


### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [49]:
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])

n = 7.0

X = np.where(nums < n, n, nums)
print(X)

[[7.   7.   7.99]
 [7.   8.32 7.  ]
 [7.   7.   9.29]]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

In [5]:
T = np.random.randint(10, size=(3, 4))
print(T)
Q = np.sum(T)
print(Q)
R = np.sum(T,axis=0)
print(R)

[[5 8 6 9]
 [5 8 7 3]
 [8 0 2 9]]
70
[18 16 15 21]


### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

In [8]:
T = np.random.randint(10, size=(3, 4))
print(T)

H = np.argwhere(T)
print(H)

[[8 6 0 8]
 [8 4 0 8]
 [4 1 5 0]]
[[0 0]
 [0 1]
 [0 3]
 [1 0]
 [1 1]
 [1 3]
 [2 0]
 [2 1]
 [2 2]]


### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

In [9]:
T = np.random.randint(10, size=(3, 4))
print(T)

Y = np.sort(T)
print(Y)

[[9 5 8 7]
 [1 2 1 7]
 [5 2 7 0]]
[[5 7 8 9]
 [1 1 2 7]
 [0 2 5 7]]


### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

In [12]:
T = np.random.randint(10, size=(3, 4))
print(T)

D = np.sum(T, axis=0)    # Column wise sum
print(D)

K = np.sum(T, axis=1)    # Row wise sum
print(K)

[[2 9 7]
 [1 1 1]
 [3 5 9]]
[ 6 15 17]
[18  3 17]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

In [14]:
T = np.random.randint(10, size=(3, 4))
print(T)

G = np.linalg.norm(T)
print(G)

norm_array = T / G

print(norm_array)

[[1 5 2 0]
 [2 1 9 7]
 [0 6 5 7]]
16.583123951777
[[0.06030227 0.30151134 0.12060454 0.        ]
 [0.12060454 0.06030227 0.54272042 0.42211588]
 [0.         0.36181361 0.30151134 0.42211588]]


### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

In [17]:
T = np.random.randint(10, size=(3, 3))
print(T)

R = np.random.randint(10, size=(3, 3))
print(R)

F = np.dot(T,R)
print(F)

[[8 2 0]
 [0 8 2]
 [5 7 0]]
[[1 5 6]
 [6 3 2]
 [3 6 2]]
[[20 46 52]
 [54 36 20]
 [47 46 44]]


### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

In [20]:
T = np.random.randint(10, size=(3, 3))
print(T)

O = np.trace(T)
print(O)

[[8 7 2]
 [8 3 6]
 [8 7 8]]
19


### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

In [25]:
T = np.random.randint(10, size=(3, 3))
print(T)
T[[0,2]] = T[[2,0]]    # Swap 0th row and 2nd row
print(T)

[[5 2 3]
 [7 5 7]
 [9 8 9]]
[[9 8 9]
 [7 5 7]
 [5 2 3]]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

In [31]:
arr = np.array([10, 20, 30, 40, 50])[np.newaxis]

U = arr.T

print(U)



[[10]
 [20]
 [30]
 [40]
 [50]]


### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

In [35]:
T = np.random.randint(10, size=(3, 3))
print(T)

L = np.linalg.det(T)
print(L)

[[8 0 1]
 [3 6 7]
 [3 1 2]]
25.000000000000007


### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

In [37]:
T = np.random.randint(10, size=(2, 2))
print(T)

Q = np.linalg.eig(T)
print(Q)

[[3 3]
 [0 1]]
EigResult(eigenvalues=array([3., 1.]), eigenvectors=array([[ 1.        , -0.83205029],
       [ 0.        ,  0.5547002 ]]))


### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

In [42]:
# 3x+6y+7z = 10, 2x+y+8z = 11 & x+3y+7z = 22: The set of linear equations to solve
a = np.array([[3,6,7],
              [2,1,8],
              [1,3,7]])

b = np.array([10,11,22])
print(a)
print(b)

c = np.linalg.solve(a,b)
print(c)

[[3 6 7]
 [2 1 8]
 [1 3 7]]
[10 11 22]
[-9.63461538  2.42307692  3.48076923]


### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

In [45]:
T = np.random.randint(10, size=(2, 2))
print(T)

noise = np.random.normal(2)
print(noise)

arra = T + noise
print(arra)

[[8 3]
 [4 0]]
4.167254793705503
[[12.16725479  7.16725479]
 [ 8.16725479  4.16725479]]


### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

In [47]:
T = np.random.randint(10, size=(4, 4))
print(T)

diag = np.diag(T, k=0)
print(diag)

[[1 0 5 5]
 [3 6 6 4]
 [8 3 7 1]
 [7 7 1 4]]
[1 6 7 4]


### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---